apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
        azure.workload.identity/use: "true"
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "sleep infinity"]
        resources:
          requests:
            cpu: '0.1'
            ephemeral-storage: 10Gi
            memory: 1Gi
          limits:
            cpu: '1'
            ephemeral-storage: 10Gi
            memory: 2Gi
        volumeMounts:
        - mountPath: /emptydir
          name: emptydir
      volumes:
      - name: emptydir
        emptyDir: {}